### PR TITLE
fix: scrape pink paw articles

### LINKED ISSUE #173: image scraping failed for specific games
example:

https://fitgirl-repacks.site/songs-of-conquest/
https://fitgirl-repacks.site/goodnight-universe/

it's likely not working for pink paw award games

### PR DESCRIPTION
**Pull request by mokurin000**
the p tag are behind  a `div` so removing the '>' rule

fix #173 

also fix recently updated scraing, see comments below

### CODE REVIEW

File: src-tauri/local-crates/fit-launcher-scraping/src/parser.rs [hunk 1]
```diff
@@ -188,7 +188,7 @@ pub fn parse_game_from_article(article: ElementRef<'_>) -> Game {
         .unwrap_or_default();
 
     let img = article
-        .select(&scraper::Selector::parse(".entry-content > p > a > img").unwrap())
+        .select(&scraper::Selector::parse(".entry-content p > a > img").unwrap())
```
Comment (mokurin000) [inline src-tauri/local-crates/fit-launcher-scraping/src/parser.rs]: `entry-content > p` in *Pink paw award* games is not possible
fitgirl added a div block for the background image

File: src-tauri/local-crates/fit-launcher-scraping/src/db/games.rs [hunk 2]
```diff
@@ -336,7 +336,9 @@ pub fn set_category_games(
         )?;
 
         tx.execute(
-            "INSERT INTO game_categories (url_hash, category, position) VALUES (?1, ?2, ?3)",
+            "
+            INSERT INTO game_categories (url_hash, category, position) VALUES (?1, ?2, ?3)
+            ON CONFLICT (url_hash, category) DO NOTHING",
```
Comment (mokurin000) [inline src-tauri/local-crates/fit-launcher-scraping/src/db/games.rs]: On insertion avoid errors even on confliction
